# Generated by Django 5.0.7 on 2024-07-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('id_teamviewer', models.CharField(blank=True, help_text="Donne l'id Teamviewer du client", max_length=255)),
                ('email', models.EmailField(blank=True, default='Non renseignée', max_length=254)),
                ('has_teleassistance', models.BooleanField(default=False, help_text='Indique si le client est abonné au service de téléassistance')),
                ('sub_start_date', models.DateField(blank=True, default='Unknown')),
                ('sub_end_date', models.DateField(blank=True, default='Unknown')),
            ],
        ),
    ]
