# Generated by Django 5.0.7 on 2024-07-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teamviewer', '0002_alter_client_sub_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sub_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='sub_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
