# Generated by Django 5.0.7 on 2024-08-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teamviewer', '0003_alter_client_sub_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='commentary',
            field=models.CharField(blank=True, help_text="Permet d'avoir plus d'info sur le client notamment si il a plusieurs ID", max_length=255),
        ),
    ]
