# Generated by Django 5.0.7 on 2024-08-31 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0002_weeklyticketstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Ouvert'), ('closed', 'Fermé')], default='open', max_length=20),
        ),
    ]
