# Generated by Django 5.0.7 on 2024-09-01 17:40

import Ticket.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0003_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='creation_date',
            field=models.CharField(default=Ticket.models.date_format_mois_jour_annee, max_length=10),
        ),
    ]
